### ISSUE TITLE
Checking Out

### ISSUE THREAD

**Issue by simonhrogers** [robmellett/shopify-nuxtjs-starter#3]
Hi Rob, 

Firstly ... thank you so much for this! It’s massively helpful for a beginner working things out. I’m working on an urgent charity fundraiser – a photographic print sale for food banks in the UK due to Covid-19. 

https://shop.photographsforthetrusselltrust.org/

The bit I’m struggling with is the checkout process which I believe is missing from your example; at the moment I can only get the createCheckout action to direct me to an empty cart on my Shopify domain. 

Any advice would be hugely appreciated – it’s supposed to go live this Monday 27th!

Thanks,

Simon

**Comment by simonhrogers** [comment]
I feel like a dummy! 

This was way easier than I imagined. I was calling your createCheckout action with obviously wiped the state and started again. It didn’t take me too long to realise... so then pushing the webUrl to the window on a button click is trivial. Thank you so much for you work on this project; 
I genuinely would not be able to do this without you and I think we will raise a lot of money! Will be sure to add your name in the Thanks section and let you know when it is live.

**Comment by robmellett** [comment]
Thank you for the kind words @simonhrogers.

I'm still working though some of the features, but it's motivating to know that people such as yourself are getting value from it.  I'll put some more time into it when when I can :)
